### ISSUE TITLE
Lian bu shang.Can not connect to the server.

### ISSUE THREAD

**Issue by MikeJinhua** [flamefox/pomelo-unitychat#1]
Transport connect 127.0.0.1 with timeout:5000
UnityEngine.Debug:Log(Object)
Pomelo.DotNetClient.TransporterTCP:Connect(IPEndPoint, Int32) (at Assets/scripts/pomelo/pomelo-dotnetclient/transport/TransporterTCP.cs:95)
Pomelo.DotNetClient.PomeloClient:Connect(String, Int32, String, Action, Action, Int32) (at Assets/scripts/pomelo/pomelo-dotnetclient/client/PomeloClient.cs:224)
pomeloBehaviour:ConnectServer(String, Int32, ClientProtocolType, String, Byte[], String, String) (at Assets/scripts/pomelo/pomeloBehaviour.cs:89)
chatofpomelo:ConnectToGate() (at Assets/chatofpomelo.cs:40)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by flamefox** [comment]
Please Use the Server at this https://github.com/NetEase/chatofpomelo-websocket
switch to the branch of tutorial-admin-module and change the version of pomelo at packages.json.
